### PR TITLE
Fix title expansion

### PR DESCRIPTION
**Pull request by akrimer**
I only wrote code in 3 files 
albumPreview.jsx 
artistPreview.jsx 
TrackPreview.jsx

so only look at changes there.

### CODE REVIEW

**Review by nathanlim1 — CHANGES_REQUESTED** [review]
Hi Aaron! Were you able to test the app after you made your changes? When I switch my branch to yours, it looks like your changes do not fix the title expansion error.

In addition, before we can merge, please make the following edits to the code:

- It looks like you deleted a necessary variable declaration in the backend.js file. Please re-add "const appFeUrl = process.env.PROD_FE_URL;" to the backend.js. Check the main branch to see where this is supposed to go if you are unsure
- Please reset maxItems (in backend.js) to the stable value of 100
- Please make sure that the branch passes the eslint checks indicated in Github. Looks like there are a couple missing dependencies in some React hooks.

**Review by nathanlim1 — CHANGES_REQUESTED** [review]
Hi Aaron! Unfortunately, it looks like the code is still not working and the titles are still expanding. I'll help you modify the branch to set it up so you can test it locally, but make sure you test your changes in the future to make sure they're fixing the issue.

**Comment by logancostello** [comment]
Hey Aaron. Code is looking good although there are some conflicting files for the merge. Please fix that up. Alternatively I also happened to tackle this problem on a different branch that I just made a pull request for. Please check mine out and we can compare code and features and whichever one we like more we will merge in.

**Comment by logancostello** [comment]
Whoops didnt mean to close. They should really add a confirmation button.

**Review by AquaJet738 — COMMENTED** [review]
yeah whatever logan said I'm going to also say, just fix the merge conflicts and talk to him about the merge

**Comment by logancostello** [comment]
This branch is going to stay open. Do not close it.

**Pull request closed without merging**
