### PR TITLE
Generate playlist function

### PR DESCRIPTION
**Pull request by AquaJet738**

### CODE REVIEW

**Review by nathanlim1 — CHANGES_REQUESTED** [review]
Hi Steven! Nice function. Before we can merge it into the branch, we'll need to fix some of the errors I'm getting. Looks like you're missing an export statement in the new file you created, but even when I fix that I get this error when attempting to generate a playlist:

chunk-L2GCM37S.js?v=2a33db6d:11501 
Uncaught (in promise) Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at useSpotifyApi (SpotifyContext.jsx:14:21)
    at generatePlaylist (generatePlaylist.js:5:22)
    at onClick (tracks.jsx:53:27)

Not sure what could be causing it, but looks like the generate playlist call isn't working properly. Let me know if you need help debugging it!

**Comment by logancostello** [comment]
Good job Steven and Nathan, however it looks like the CI tests are failing (the automatic tests). Typically these errors are trivial, such as unused variables and lines of code that are too long. Please update to pass the tests then it will be good to merge!

**Review by akrimer — APPROVED** [review]
hey! code looks on point for the functions 
changing the const maxItems = 100; // max items to load from Spotify API calls and lowering it also helped me load it. overall your code looks pretty good so I think a proper LGTM is in order. 

the play list is going to be sooo good. Great job !!

**Review by luke-villaluz — APPROVED** [review]
Added all the necessary stuff to generate playlists! Spotify wrapped is late this year, so this is perfect timing. Maybe later we can make it so it generates a playlist of all top tracks returned upon loading instead of ones displaying, although I do like the current idea.

**Comment by nathanlim1** [comment]
> hey! code looks on point for the functions changing the const maxItems = 100; // max items to load from Spotify API calls and lowering it also helped me load it. overall your code looks pretty good so I think a proper LGTM is in order.
> 
> the play list is going to be sooo good. Great job !!

Hi Aaron! Thanks for the response. I think that the maxItems = 100 might be another issue. We're trying to up it to more hundreds in the future before we present, so 200 for now is probably fine.

**Comment by nathanlim1** [comment]
> Added all the necessary stuff to generate playlists! Spotify wrapped is late this year, so this is perfect timing. Maybe later we can make it so it generates a playlist of all top tracks returned upon loading instead of ones displaying, although I do like the current idea.

Thanks Luke! Saw that you merged the branch after reviewing. Thanks!

**Pull request merged**
